name: Test Matrix

on:
  push:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable --network-timeout 1000000

      - name: Run "build" step
        run: NODE_OPTIONS=--max-old-space-size=4096 yarn tsc && yarn copy:build

      - name: Run  Lint
        run: NODE_OPTIONS=--max-old-space-size=4096 yarn lint

      - name: 'Tar files'
        run: tar -cvf js_files.tar --exclude=node_modules --exclude=dist ./build

      - name: Upload built Javascript files
        uses: actions/upload-artifact@v2
        with:
          name: js-build
          path: js_files.tar
          retention-days: 1

  test:
    name: Test Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    needs: lint
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [14, 16]
        include:
          - node-version: 16.x
            os: ubuntu-latest
            browser: chrome-97-0

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Download built typescript files
        uses: actions/download-artifact@v2
        with:
          name: js-build
          path: .

      - name: Untar files
        run: tar -xf js_files.tar

      - name: Copy mitm source
        run: cp -r mitm-socket/go build/mitm-socket/go

      - name: Build modules
        run: yarn --network-timeout 1000000
        working-directory: ./build
        env:
          SA_REBUILD_MITM_SOCKET: 1

      - name: Linux - Add Chrome Env
        if: ${{ matrix.browser }}
        working-directory: ./build
        run: yarn add -W @ulixee/${{ matrix.browser }}

      - name: Linux - Apt Install Chrome(s)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: ./build
        run: sudo $(npx install-browser-deps)

      - name: Run tests
        run: yarn test --testTimeout=60000 --maxWorkers=2
        working-directory: ./build
        env:
          SA_DEFAULT_BROWSER_ID: ${{ matrix.browser }}

      - name: 'Tar files'
        if: ${{ failure() }}
        run: tar -cvf test-output.tar ./build/.data-test

      - name: Upload Databases
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-output-${{matrix.os}}-${{ matrix.node-version }}
          path: test-output.tar
          retention-days: 1
